config/routes.rb
Mccspain::Application.routes.draw do
  match '/home', :to => 'pages#home'
  
  root :to => 'pages#home'

  resources :pages do
    collection do
      get 'download_file'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def download_file
    send_file "public/downloads/" + params[:file], :type => "application/pdf"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <meta name="author" content="Fundació CREAL">
  <meta name="Copyright" content="CREAL">
  <meta name="description" content="MCC Spain">
  <meta name="Keywords" content="">

  <title>MCC Spain</title>

  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

  <link rel="stylesheet" href="stylesheets/style.css" type="text/css" media="all">
  <link rel="stylesheet" href="stylesheets/print.css" type="text/css" media="print">
  <link rel="stylesheet" href="stylesheets/mccspain_style.css" type="text/css" media="screen">
  <!--[if IE]><link rel="stylesheet" href="/media/css/ie.css" type="text/css" media="all"/><![endif]-->
  <!--[if IE 7]><link rel="stylesheet" href="/media/css/ie7.css" type="text/css" media="all"/><![endif]-->
  <!--[if lte IE 6]><link rel="stylesheet" href="/media/css/ie6.css" type="text/css" media="all"/><![endif]-->
  <!--[if IE 8]><link rel="stylesheet" href="/media/css/ie8.css" type="text/css" media="all"/><![endif]-->

  <!-- 
  <script type="text/javascript" src="mccspain.php_files/jquery-1.js"></script>
  <script type="text/javascript" src="mccspain.php_files/jquery.js"></script>
  <script type="text/javascript" src="mccspain.php_files/base.js"></script>
  -->

  <!-- Png fix -->
  <!--[if lte IE 6]>
  <script type="text/javascript" src="/media/js/dd_belatedpng.min.js"></script>
  <script type="text/javascript">
	  DD_belatedPNG.fix('img, #iconot, #icoact, div.fancy_bg_e, div.fancy_bg_w, div.fancy_bg_s, div.fancy_bg_n, div.fancy_bg_sw, div.fancy_bg_nw, div.fancy_bg_ne, div.fancy_bg_se');
  </script>
  <![endif]-->
</head>

<body id="noticies" class="fitxa">
	<div id="container_main">
		<!-- CAPSALERA -->
		<div id="acc">
			<ul>						
				<li><a href="#content_main" accesskey="S">Skip to content</a></li>
				<li><a href="#nav_main">Skip to main navigation</a></li>
				<li><a href="#nav_sub">Skip to secondary navigation</a></li>
			</ul>
		</div>
		<hr>
		<!-- /acc -->
		<div id="branding">
		  <table>
		    <tr>
		      <td id="logo">
			      <h1><img src='images/mccspain_logo.jpg'></h1>
			    </td>
			    <td id="logo_txt">
			      <h1>Estudio multi-caso control poblacional, incluyendo tumores de alta incidencia en España</h1>
			    </td>
			  </tr>
			</table>
			<hr>
			<div id="eines">
				<ul id="idiomes">
					<li><a href="http://www.creal.cat/programes-recerca/projectes-creal/view.php?ID=61&amp;prog=0" title="Versió en Català" hreflang="ca" xml:lang="ca">Català</a></li>
					<li><a href="http://www.creal.cat/programes-recerca/es_projectes-creal/view.php?ID=61&amp;prog=0" title="Versión en castellano" hreflang="es" xml:lang="es">Castellano</a></li>
					<li>English</li>
				</ul>
			</div>
		</div>
		<hr>
		<!-- /branding -->
		
		<!-- / CAPSALERA -->
		
		<div id="container_sub">
			<div id="content_main">
				<p class="data">National</p>

				<ul id="dades_projecte" class="clearfix">
					<li class="lidurada"><strong>Duration: </strong><br>2009-2011</li>
					<li class="licoordinador"><strong>Coordinator: </strong><br> Manolis Kogevinas</li>
					
					<li class="lifinancador">
					  <div id="divfinancadors"><p><strong>Funded by: </strong><br></p>
					    <div class="text">
      					<ul>
                  <li><a class="external" target="_blank" href="http://www.ciberesp.es/" rel="external">CIBERESP</a></li>
                  <li><a class="external" target="_blank" href="http://www.isciii.es/jsps/organizacion/evaluacion_fomento/convocatorias/Fondo_convocatorias_plantillable.jsp" rel="external">FIS</a></li>
                </ul>
              </div>
            </div>
          </li>
				</ul>				
			  <%= yield %>
			</div>
			<!-- /content_main -->
		</div>
		<!-- /container_sub -->
		
		<div id="content_sub">
			<div class="box">
			  <ul>
			    <li><a href="http://www.creal.cat/programes-recerca/en_projectes-creal/view.php?ID=61&amp;SKIN=1&amp;prog=0">Group members</a></li>
			    <li><a href="http://www.creal.cat/programes-recerca/en_projectes-creal/view.php?ID=61&amp;SKIN=2&amp;prog=0">Publications</a></li>
  	    </ul>
  	    <span class="t"></span>
  	    <span class="b"></span>
  	  </div>
			
			<div class="box contacte">
			  <h2>CONTACT</h2>
			  <p><strong>Main investigator: </strong><br>Manolis Kogevinas</p><p><strong>Teléfono: </strong><br>93 214 73 30</p><p><strong>Email: </strong><br><a href="mailto:kogevinas@creal.cat">kogevinas@creal.cat</a></p><span class="t"></span><span class="b"></span><span class="pict"></span>
  	  </div>
				
		</div>
		<hr>
		<!-- /content_sub -->
		<!-- PEU-->
		<div id="site_info" class="clearfix">
    	<p class="vcard">
    	  <span class="fn org">CREAL</span> · <span class="adr"><span class="street-address">Doctor Aiguader, 88</span> · <span class="postal-code">E-08003</span> <span class="locality">Barcelona</span></span> · Tel <span class="tel">+34 93 214 73 00</span> · Fax <span class="fax">+34 93 214 73 02</span> · e-mail: <a href="mailto:info@creal.cat" class="email">info@creal.cat</a> <span class="rss_peu"></span>
   	  </p>
    </div>
    <!-- /site_info -->
  	<!--  /PEU -->
	</div>
	<!-- /container_main -->
</body>
</html>

app/views/pages/home.html.erb
<p>In 2008, the CIBERESP, within the framework of Cross-Sectional 
Action in Cancer, provided the resources to launch a population-based <strong>multicase-control study </strong>(MCC-SPAIN)
 in order to research the influence of environmental factors and their 
interaction with genetic factors in frequent tumours or tumours with 
peculiar epidemiological characteristics in our country, in which the 
environmental factors involved are not sufficiently understood.</p>

<p>The selected tumours are <strong>colorectal cancer, breast cancer, gastroesophageal cancer and prostate cancer</strong>. <strong>Chronic lymphocytic leukaemia (CLL) h</strong>as
 been recently added to the study. Colorectal cancer has been selected 
due to its frequency in both sexes. Gastroesophageal cancer has been 
selected due to its characteristic geographic pattern and the 
environmental hypotheses suggested. Prostate cancer has been chosen due 
to its frequency and its hormonal nature, sharing with breast cancer the
 etiological hypotheses of endocrine disruption. The study involves data
 collection using an interview as well as the obtention of several 
biological samples. The population controls have been selected from 
primary care centre lists and interviews are performed in these centres.</p>

<p>The MCC-Spain study has also been backed by funding from the FIS during the 2009-2011 period.</p>

<p><strong>Organization</strong></p>

<p>CREAL is the coordinator centre of MCC-Spain in direct collaboration 
with the ISCII (Madrid). The study is organized in working groups that 
include water contaminants, occupation, endocrine disruptors, 
medication, tumour clinical symptoms and markers, infections, screening 
and genetics.</p>

<p>The MCC-Spain study is coordinated by Manolis Kogevinas (CREAL), 
Marina Pollan (ISCIII) and a coordinator committee, with the 
participation of representatives of all CIBERESP nodes where the study’s
 cases and controls are collected.</p>

<p><strong>Objectives</strong></p>

<p>The general objective of the study is to assess environmental and 
genetic factors associated with colorectal, breast, stomach/esophageal 
and prostate cancer.</p>

<p>The specific objectives are:</p>

<ol>
    <li>To assess the cancer risk of every tumour site in relation to 
environmental exposures including drinking water contaminants (arsenic, 
nitrates, chrome, chlorination by-products), hormonal disruptors and 
other persistent organic contaminants.</li>
    <li>To assess cancer risks related to the consumption of statins and analgesics.</li>
    <li>To assess the risk of breast and prostate cancer related to 
hormonal factors, infections and permanent phenotypes (digit ratio 
2d:4d; anogenital distance) related with environmental exposures in 
early stages of life.</li>
    <li>To validate the assessment of exposure to environmental chemical
 agents by means of exposure models using exposure biomarkers, 
individual information and environmental exposure measurements.</li>
    <li>To assess a limited series of genes in relation both to primary effects and to their interaction with environmental factors.</li>
    <li>To store sufficient biologic material for its use in future GWAS (genome wide association studies) studies and others.</li>
</ol>

<p>Researchers from the CIBERESP in 11 autonomous communities of Spain 
(Catalonia, Madrid, Asturias, Navarra, Basque Country, Murcia, 
Cantabria, Andalusia, Valencia, Castilla y Leon) are participating in 
the study. Up until March 2010 information and biologic samples were 
obtained from 1,600 population controls, 1,200 colon and rectum cases, 
750 breast cancer cases, 450 prostate cancer cases, 120 stomach cancer 
cases, and the collection of leukaemia cases was initiated.</p>

<p>If you wish to see the study protocol, click
  <%= link_to "here", download_file_pages_path(:file => "PROTOCOLOESTUDIOMCCmarzo2010.pdf") %>.
</p>

<p>If you wish to view the questionnaire, click
  <%= link_to "here", download_file_pages_path(:file => "cuestionarioMCCSpmarzo2010.pdf") %>.
</p>

<p>You can access a brief presentation by clicking
  <%= link_to "here", download_file_pages_path(:file => "Folder presentacion6.pdf") %>.
</p>

<p>To view the map of hospitals that are participating in this project, click
  <%= link_to "here", download_file_pages_path(:file => "Hospitalesparticipantes.pdf") %>.
</p>

<p>To view the list of collaborators, click
  <%= link_to "here", download_file_pages_path(:file => "Listado participantes MCC_Oct10.doc") %>.
</p>